@startuml

actor visitor as "来訪者"
participant tb as "TicketBooth"
participant t as "Ticket"
participant policy as "IUsagePolicy"
participant ti as "TicketInventory"

visitor -> tb: お金を渡す\n(buyOneDayTicket())
activate tb
tb -> tb: 購入処理を行う\n（doBuyTicket())
tb -> ti: 在庫数を尋ねる
ti --> tb: 在庫数を返す

alt 在庫あれば
    tb -> ti: 在庫を1減らす\n(getQuantity)
    tb --> visitor: 購入成功を返す\n(TicketResult)
else
    tb -> visitor: 購入失敗を返す\n(decreaseQuantity)
end

deactivate tb

visitor -> t: チケット利用(doInPark())
t -> policy: 利用可否を尋ねる\n(validate())
alt 利用可能
    t -> t: 使用回数を増やし、利用中にする
    
end
